# We are using Playwright but you may use your E2E framework of choice
name: Playwright Tests

on: [deployment_status]

jobs:
  test:
    name: Run E2E Tests
    timeout-minutes: 15
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    env:
      BASE_URL: ${{ github.event.deployment_status.target_url }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7.25.0

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --prefer-offline --frozen-lockfile

      - run: pnpm dlx playwright install

      - name: Run tests for kitchensink
        run: pnpm test:e2e:kitchensink
        if: contains(github.event.deployment_status.description, 'kitchensink')

      - name: Run tests for web
        run: pnpm test:e2e:web
        if: contains(github.event.deployment_status.description, 'web')
